# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: SAP.sap-iac
PackageVersion: 0.1.0
PackageLocale: en-US
Publisher: SAP SE
# PublisherUrl: https://sap.github.io/iac-spec-kit-for-sap-business-ai-platform/
PublisherSupportUrl: https://github.com/SAP/iac-spec-kit-for-sap-business-ai-platform/issues
PackageName: sap-iac
PackageUrl: https://sap.github.io/iac-spec-kit-for-sap-business-ai-platform/
License: Apache-2.0
LicenseUrl: https://github.com/SAP/iac-spec-kit-for-sap-business-ai-platform/blob/HEAD/LICENSE
Copyright: Copyright © 2026
ShortDescription: A toolkit to generate necessary project structure and skills for AI agents to help generate IaC(Terraform) configuration for SAP Business AI Platform.
Description: |-
  The Infrastructure-as-Code Specification Toolkit for SAP Business AI Platform is an open-source CLI tool that will help SAP Business AI Platform administrators and practitioners manage their infrastructure efficiently.
  The IaC Spec Kit for SAP Business AI Platform (sap-iac CLI) is a tool that helps you generate the necessary project structure and skills for AI agents to create IaC(Terraform) configurations for SAP Business AI Platform.
  It will provide an easy entry point for new administrators who may be new to SAP best practices and to following the right approaches when using IaC (Terraform) scripts.
Tags:
- btp
- cf
- cloudfoundry
- iac
- opentofu
- sap
- terraform
- tf
- SAP
- ai
- infrastructure-as-code
- iac-spec-kit
- sap-business-ai-platform
ReleaseNotesUrl: https://github.com/SAP/iac-spec-kit-for-sap-business-ai-platform/releases/tag/v0.1.0
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://sap.github.io/iac-spec-kit-for-sap-business-ai-platform/
ManifestType: defaultLocale
ManifestVersion: 1.10.0